services:
  postgres:
    image: postgres:15-alpine
    container_name: shop-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  seq:
    image: datalust/seq:latest
    container_name: shop-seq
    ports:
      - "5341:80"     # Web UI
      - "5342:5341"   # Ingestion API
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "SuperSecret123"
    volumes:
      - seq_data:/data

volumes:
  postgres_data:
  seq_data:
